apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.api.name }}-service"
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.api.port }}
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.containerPort }}
      targetPort: {{ .Values.postgres.containerPort }}
  type: ClusterIP
